[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "836897fa97c487adc2bda049444255887d5a3fc9"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "4dc09bf50e3a1d3c8624ebf47be2eb90534c9d92fea94fa6c7212f36e79715da"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.0+1/libNVVM.v4.0.0.x86_64-linux-gnu.tar.gz"
[[libNVVM]]
arch = "powerpc64le"
git-tree-sha1 = "79faac25f0ef313314e3d3245e1c2a6b308f6b2e"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "787490129ee1f7fab67d0bab2d14b6653baba72b87f07d99819d225d1ae2f508"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.0+1/libNVVM.v4.0.0.powerpc64le-linux-gnu.tar.gz"
[[libNVVM]]
arch = "aarch64"
git-tree-sha1 = "7dafa7af196db27bacf33a2987c38ac2b4477d19"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "a90012c0453cf57866ed560319b3347cb011648bdaf9aac6d61c1c8ec92638fb"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.0+1/libNVVM.v4.0.0.aarch64-linux-gnu.tar.gz"
[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "56d658219645d05e87c0cdeb2be376178bcd29d2"
os = "windows"

    [[libNVVM.download]]
    sha256 = "11325066efbf7f1c84776fa8d047abd6902978e594082358430bd7f908fde0fd"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.0+1/libNVVM.v4.0.0.x86_64-w64-mingw32.tar.gz"
