[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "308d798057727f496e6601938af8934760f30972"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "f7739129cd774e1f8544876b66fe70e4cba25d291cdda96f90aaa079396c4aab"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.3+0/libNVVM.v4.0.3.x86_64-linux-gnu.tar.gz"
[[libNVVM]]
arch = "aarch64"
cuda_platform = "jetson"
git-tree-sha1 = "a1507046939409eb3ab8138b1f511ed7ae0276e1"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "e95cf6fc347c7de10aa05946536ce6c6336377c2a575999fe41d63313a8763d7"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.3+0/libNVVM.v4.0.3.aarch64-linux-gnu-cuda_platform+jetson.tar.gz"
[[libNVVM]]
arch = "aarch64"
cuda_platform = "sbsa"
git-tree-sha1 = "1bc24609757d90197568bd3cdf45573c142443ff"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "c8ac5b1af16cd3eeb382cfa38492e9f76406563377f8748b400d62d17f64be31"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.3+0/libNVVM.v4.0.3.aarch64-linux-gnu-cuda_platform+sbsa.tar.gz"
[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "fc43472c69db003edfad3f4a0f012fd841b24fee"
os = "windows"

    [[libNVVM.download]]
    sha256 = "d02e6b2ab8a71693cd1d1e64a617493f033f3e415af460aa25247c2291e49b97"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.3+0/libNVVM.v4.0.3.x86_64-w64-mingw32.tar.gz"
