[[libNVVM]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "fb7ad7352704eb287fe9e18e9a05f490c241dbec"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "b816bbc23cd038933c71adc86515effb6593c696ea3c13e9883d6ed436bab1cd"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.7+0/libNVVM.v4.0.7.x86_64-linux-gnu-cuda+13.tar.gz"
[[libNVVM]]
arch = "aarch64"
cuda = "13"
git-tree-sha1 = "3086f90ee84ba7f3a3210c07b782a046e5bffd34"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "946b3a5b115d978788758b4a31c146988b5c477aeb5ad57e59274f29cc9bfec1"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.7+0/libNVVM.v4.0.7.aarch64-linux-gnu-cuda+13.tar.gz"
[[libNVVM]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "2301b6fa711db61def625b9648224a23ecaf943c"
os = "windows"

    [[libNVVM.download]]
    sha256 = "0e6887a08a3588f3b24eb12737686e1015ec309ae0b666c1bd9536e49ef3857e"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.7+0/libNVVM.v4.0.7.x86_64-w64-mingw32-cuda+13.tar.gz"
