[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "630c88a1c0813aaad76a180b6a10ad2187b1d094"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "3b98bbf7faaaffd7004102a220a59ff16bfb61cef73cc6a3182caec8e9721503"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.5+0/libNVVM.v4.0.5.x86_64-linux-gnu.tar.gz"
[[libNVVM]]
arch = "aarch64"
git-tree-sha1 = "df2ed7b9fc047fb05d8d935454561c443bef2464"
libc = "glibc"
os = "linux"

    [[libNVVM.download]]
    sha256 = "fe6e99f579e4e9c206084ec9125703812366cd5808fb53ec6f1a9e3c9fb936fd"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.5+0/libNVVM.v4.0.5.aarch64-linux-gnu.tar.gz"
[[libNVVM]]
arch = "x86_64"
git-tree-sha1 = "9c7728020c5914bee24ec34c3fea6fa15c0e7b70"
os = "windows"

    [[libNVVM.download]]
    sha256 = "32bd60f427e2a7f3cb1633ac62d0ab9661d550121a97c1a8abe54c4dc179d7f2"
    url = "https://github.com/JuliaBinaryWrappers/libNVVM_jll.jl/releases/download/libNVVM-v4.0.5+0/libNVVM.v4.0.5.x86_64-w64-mingw32.tar.gz"
