# Autogenerated wrapper script for libNVVM_jll for x86_64-w64-mingw32
export libnvvm

JLLWrappers.@generate_wrapper_header("libNVVM")
JLLWrappers.@declare_library_product(libnvvm, "nvvm64_40_0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libnvvm,
        "bin\\nvvm64_40_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
